aliases:
    apply-sabre: nix run --impure home-manager/master -- -b bak switch --flake .#spytec@sabre
    fleeks: cd ~/.local/share/fleek
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: high
blocklist: []
byo_git: false
ejected: true
flakedir: .local/share/fleek
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - neovim
    - ripgrep
    - bat
    - gphoto2
    - devpod
    - devbox
    - sqlite
    - git
    - gh
    - yarn
    - nodejs
    - sunshine
    - zsh
    - vagrant
    - hyfetch
    - zsh-fzf-tab
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: sabre
      os: linux
      user:
        email: freya@spytec.se
        name: Freya Gustavsson
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: spytec
      username: spytec
track: nixos-unstable
unfree: true
users: []
